### ISSUE TITLE
Render a simple mesh

### ISSUE THREAD

**Issue by Korijn** [almarklein/visvis2#5]
We left master in a broken state during last friday's refactoring session; let's get it to the point where can render a simple mesh again.

**Comment by almarklein** [comment]
In #6 I (more or less) have the triangle working again. But need some more work to get meshes working. Would you like me to split this up so we have a working master sooner?

**Comment by Korijn** [comment]
That would probably be a good idea :)

**Comment by almarklein** [comment]
reopening: not there yet :)

**Comment by almarklein** [comment]
We can now render a mesh in one color or with a texture. No lighting yet. Let's track that in #29
